ai/urls.py
# coding: utf-8

from django.conf.urls import url
import views


urlpatterns = [
    url(r'^$', views.index),
    url(r'^face_recognite/$', views.face_recognite),
]

blog/urls.py
# coding: utf-8

from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^tags/$', views.get_tags, name='tags'),
    url(r'^categorys/$', views.get_categorys, name='categorys'),
    url(r'^(?P<id>(\d+))/$', views.detail),
]

smart_pps_service/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view

from member.views import UserViewSet, OrganizationViewSet, GroupViewSet
from pps.views import ProductViewSet, OrderViewSet
from blog import views as blog_views
from game.views import GameViewSet
from comic.views import ComicViewSet
from music.views import MusicViewSet
from baby_daily.views import DailyPerformViewSet
from wechat.views import LoginView
from aliyun_oss import views as aliyun_oss_views
import views

schema_view = get_swagger_view(title='One Service Rest API')

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'articles', blog_views.ArticleViewSet, 'articles')
router.register(r'orgs', OrganizationViewSet, 'orgs')
router.register(r'groups', GroupViewSet, 'groups')
router.register(r'users', UserViewSet, 'users')
router.register(r'products', ProductViewSet, 'products')
router.register(r'orders', OrderViewSet, 'orders')
router.register(r'games', GameViewSet, 'games')
router.register(r'comics', ComicViewSet, 'comics')
router.register(r'musics', MusicViewSet, 'musics')
router.register(r'performs', DailyPerformViewSet, 'performs')

urlpatterns = [
    url(r'^$', views.index),
    # social
#    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^game/', include('game.urls', namespace='game')),
    url(r'^ai/', include('ai.urls', namespace='ai')),
    url(r'^comic/', include('comic.urls', namespace='comic')),
    url(r'^music/', include('music.urls', namespace='music')),
    url(r'^baby/', include('baby_daily.urls', namespace='baby_daily')),
    url(r'^crawler', include('crawler.urls')),
    url(r'^manage$', views.manage),
    url(r'^manage/blogs', blog_views.manage),
    url(r'^manage/aliyun_oss', include('aliyun_oss.urls')),
    url(r'^manage/crawler', include('crawler.urls')),
    url(r'^proj$', views.proj),
    url(r'^plan$', views.plan),
    url(r'^about$', views.about),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^docs', schema_view),
    url(r'^wx_login', LoginView.as_view()),
    # oss
    url(r'^aliyun_oss/', include('aliyun_oss.urls')),
    url(r'^oss_media/(?P<fid>[0-9a-zA-Z\-]+)', aliyun_oss_views.read),
    # url(r'^short_link/', include('short_link.urls')),
    url(r'^api/', include(router.urls)),
    # notifications
    url('^inbox/notifications/', include('notifications.urls', namespace='notifications')),
    # activity
    url(r'^activity/', include('actstream.urls')),
    # account
    # url(r"^account/", include("account.urls")),
    url(r'^mdeditor/', include('mdeditor.urls'))
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#
#handler404 = views.page_not_found
#handler500 = views.page_error

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from mdeditor.fields import MDTextField


class Article(models.Model):
    title = models.CharField(max_length=20, verbose_name='标题')
    content = MDTextField(blank=True, verbose_name='内容')
    category = models.CharField(max_length=20, blank=True, verbose_name='分类')
    tags = models.CharField(max_length=20, blank=True, verbose_name='标签')
    is_published = models.BooleanField(default=False, verbose_name='是否发布')
    author = models.ForeignKey(User, verbose_name='作者')
    pv = models.IntegerField(verbose_name='pv', default=0)
    uv = models.IntegerField(verbose_name='uv', default=0)
    is_recommend = models.BooleanField(verbose_name='是否推荐', default=False)
    crt = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    upt = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status, filters, permissions
from rest_framework.response import Response

from common import BasePagination
from smart_pps_service.common import viewsets
from smart_pps_service.common.common import md_2_html2, xresult
import serializers
from models import Article
from tasks import increate_pv


def index(request):
    return render(request, 'blog/index.html')


@login_required
def manage(request):
    return render(request, 'blog/manage.html')


def detail(request, id):
    try:
        obj = Article.objects.get(id=id)
        increate_pv(id)
    except Exception as e:
        pass
    html5_content = md_2_html2(obj.content)
    return render(request, 'blog/detail.html', {
        'id': obj.id,
        'title': obj.title,
        'category': obj.category,
        'tags': obj.tags.split(','),
        'pv': obj.pv,
        'upt': obj.upt,
        'content': html5_content.replace('<table>', '<table class="table table-bordered table-striped">')
    })


@csrf_exempt
def get_categorys(request):
    categorys = list(set(Article.objects.filter(is_published=True).values_list('category',
                                                           flat=True)))
    if len(categorys[0]) == 0:
        categorys.remove(categorys[0])
    return JsonResponse(data=xresult(data=categorys))


@csrf_exempt
def get_tags(request):
    tags = ",".join(Article.objects.filter(is_published=True).values_list('tags', flat=True))
    tags = list(set(tags.split(',')))
    if len(tags[0]) == 0:
        tags.remove(tags[0])
    return JsonResponse(data=xresult(data=tags))


class ArticleViewSet(viewsets.ModelViewSet):

    queryset = Article.objects.filter(is_published=True)
    filter_backends = (filters.SearchFilter,)
    search_fields = ('=category', 'tags')
    serializer_class = serializers.ArticleSerializer
    pagination_class = BasePagination
    permission_classes = (permissions.AllowAny,)

    def create(self, request, *args, **kwargs):
        data = request.data
        data['author'] = request.user.id
        serializer = self.get_serializer(data=data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

blog/templates/blog/blog_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel='stylesheet' href='../../static/css/bootstrap.min.css' type='text/css'/>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
        <img src="/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
        Bootstrap
      </a>
    </nav>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Library</a></li>
        <li class="breadcrumb-item active" aria-current="page">Data</li>
      </ol>
    </nav>
    <div class="container">
     <div class="list-group">
  <a href="#" class="list-group-item active">
    <h4 class="list-group-item-heading">List group item heading</h4>
    <p class="list-group-item-text">...</p>
  </a>
         <a href="#" class="list-group-item">
    <h4 class="list-group-item-heading">List group item heading</h4>
    <p class="list-group-item-text">...</p>
  </a>
         <a href="#" class="list-group-item">
    <h4 class="list-group-item-heading">List group item heading</h4>
    <p class="list-group-item-text">...</p>
  </a>
</div>
        <nav aria-label="Page navigation example">
                      <ul class="pagination">
                        <li class="page-item">
                          <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                          </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                          <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                          </a>
                        </li>
                      </ul>
                    </nav>
    </div>


<script type="text/javascript" src="../../static/js/bootstrap.min.js"></script>
</body>
</html>

blog/templates/blog/common.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

blog/templates/blog/detail.html
{% extends 'common/base.html' %}
{% load static %}
{% block content %}

    <!-- Start of Page Container -->
    <div class="page-container">

        <div class="container">
            <div class="row">
                <!-- start of page content -->
                <aside class="span12 page-sidebar">
                    <h1>{{ title }}</h1>
                    <p>分类：{{ category }}
                        标签：{% for tag in tags %}
                            {{ tag }}
                        {% endfor %}
                        </p>
                    <p>更新时间：{{ upt | date:"Y-m-d" }} 浏览次数：{{ pv }}</p>
                </aside>
            </div>
            <div class="row">
                <aside class="span8 page-sidebar">
                    {% autoescape off %}
                        {{ content }}
                    {% endautoescape %}
                </aside>
                <aside class="span4 page-sidebar">
                </aside>
            </div>
            <div class="row">
                <aside class="span12 page-sidebar">
                    <h1>留言</h1>
                </aside>
            </div>
        </div>
    </div>
    <!-- End of Page Container -->

{% endblock %}

blog/templates/blog/index.html
{% extends 'common/base.html' %}
{% load static %}
{% block content %}

<style>
.comic-body {
    width: 1070px;
    margin: 0 auto;
    padding-top: 20px;
    padding-bottom: 20px;"
}
</style>

{% verbatim %}
<div id="app" class="comic-body">
    <el-row :gutter="24">
        <el-col :span="6">
            <div style="margin-top: 15px;">
                <el-input placeholder="请输入内容" v-model="search" class="input-with-select">
                    <el-option label="餐厅名" value="1"></el-option>
                    <el-option label="订单号"
                               value="2"></el-option>
                           <el-option label="用户电话"
                                      value="3"></el-option>
                </el-select>
                <el-button
                                      slot="append"
                                      icon="el-icon-search"></el-button>
        </el-input>
            </div>
    </el-col>
    </el-row>
    <el-row :gutter="24">
        <el-col :span="6">
            <el-card class="box-card" :body-style="{ padding: '5px' }" :style="{ margin: '15px 0 15px 0' }">
                <div slot="header" class="clearfix">
                    <span>分类</span>
                </div>
                <el-tag :style="{ margin: '5px' }" size="small" v-for="category
                    in categorys" :key="category">{{category}}</el-tag>
            </el-card>
            <el-card class="box-card" :body-style="{ padding: '5px' }" :style="{ margin: '15px 0 15px 0' }">
                <div slot="header" class="clearfix">
                    <span>标签</span>
                </div>
                <el-tag :style="{ margin: '5px' }" size="small" v-for="tag in
                tags" :key="tag">{{tag}}</el-tag>
            </el-card>
        </el-col>
        <el-col :span="18">
            <el-card :style="{ margin: '15px 0 15px 0' }" shadow="hover"
                v-for="article in articles" :key="article.id">
                <div>
                    <h3><a
                v-bind:href="'/blog/' + article.id + '/'">{{article.title}}</a></h3>
                    <p>作者：{{article.author_name}} 浏览 {{article.pv}} 更新时间：{{article.upt}} </p>
                </div>
            </el-card>
            <div class="block">
                <el-pagination
                    background
                    @current-change="fetchArticles"
                    :current-page.sync="pager.page"
                    :page-size="20"
                    layout="total, prev, pager, next"
                    :total="pager.total">
                 >
                </el-pagination>
            </div>
        </el-col>
    </el-row>
</div>
{% endverbatim %}
<script>
new Vue({
    el: '#app',
    data: function () {
        return {
            search: '',
            visible: false,
            articles: [],
            tags: [],
            categorys: [],
            pager: {
                total: 0,
                page: 1
            }
        }
    },
    created: function () {
        this.fetchTags();
        this.fetchCategorys();
        this.fetchArticles();
    },
    methods:{
        fetchArticles: function (page) {
            var _self = this;
            if (page == undefined) {
                page = _self.pager.page;
            }
            var queryStr = '?page={page}'.format({ page: page });
            _self.$http.get('/api/articles' + queryStr).then(function (res) {
                _self.articles = res.data.results;
                _self.pager.total= res.data.count;
                _self.pager.page = page;
            }, function () {
                console.log('请求失败处理');
            });
        },
        fetchTags: function () {
            var _self = this;
            //发送get请求
            _self.$http.get('{% url "blog:tags" %}').then(function (res) {
                _self.tags = res.data.data;
            }, function () {
                console.log('请求失败处理');
            });
        },
        fetchCategorys: function () {
            var _self = this;
            //发送get请求
            this.$http.get('{% url "blog:categorys" %}').then(function (res) {
                _self.categorys = res.data.data;
            }, function () {
                console.log('请求失败处理');
            });
        }

    }
})
</script>
{% endblock %}

blog/templates/blog/list.html
{% extends 'common/base.html' %}
{% load static %}
{% block content %}

{#    <style>#}
{#        .note-list {#}
{#            margin: 0;#}
{#            padding: 0;#}
{#            list-style: none;#}
{#        }#}
{##}
{#        .note-list li.have-img {#}
{#            min-height: 140px;#}
{#        }#}
{##}
{#        .note-list li {#}
{#            position: relative;#}
{#            width: 100%;#}
{#            margin: 0 0 15px;#}
{#            padding-right: 2px;#}
{#            border-bottom: 1px solid #f0f0f0;#}
{#            word-wrap: break-word;#}
{#        }#}
{##}
{#        .note-list .have-img>div {#}
{#            padding-right: 140px;#}
{#        }#}
{##}
{#        .title {#}
{#            font-family: -apple-system,SF UI Display,Arial,PingFang SC,Hiragino Sans GB,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif;#}
{#        }#}
{##}
{#        .note-list .have-img .wrap-img {#}
{#            position: absolute;#}
{#            top: 50%;#}
{#            margin-top: -60px;#}
{#            right: 0;#}
{#            width: 125px;#}
{#            height: 100px;#}
{#        }#}
{##}
{#        .note-list .title {#}
{#            margin: -7px 0 4px;#}
{#            display: inherit;#}
{#            font-size: 18px;#}
{#            font-weight: 700;#}
{#            line-height: 1.5;#}
{#        }#}
{##}
{#        img {#}
{#            vertical-align: middle;#}
{#        }#}
{##}
{#        div {#}
{#            display: block;#}
{#        }#}
{##}
{#        li {#}
{#            line-height: 20px;#}
{#            display: list-item;#}
{#            text-align: -webkit-match-parent;#}
{#        }#}
{#    </style>#}
    <!-- Start of Page Container -->
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <!-- Navbar content -->
    </nav>
    <div class="page-container">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Library</a></li>
            <li class="breadcrumb-item active" aria-current="page">Data</li>
          </ol>
        </nav>
        <div class="container">
            <div class="row">
                <!-- start of page content -->
                <aside class="span8 page-sidebar">
                    <ul class="note-list" id="list_content">
                        <li id="note-28491853" data-note-id="28491853" class="have-img">
{#                            <a class="wrap-img" href="/p/3b4b5ac2ea68" target="_blank">#}
{#                              <img class="  img-blur-done" src="//upload-images.jianshu.io/upload_images/3343569-4bcf991e16d299a1?imageMogr2/auto-orient/strip|imageView2/1/w/300/h/240" alt="120">#}
{#                            </a>#}
                          <div class="content">
                            <a class="title" target="_blank" href="/p/3b4b5ac2ea68">山城重庆 | 桥上之城的都市风光</a>
                            <p class="abstract">
                              随处可见的长江大桥 全国的城市里，只有重庆的长江大桥最多，建好的有36座。重庆是个两江环绕的山城，桥担负着行车、行人、行轻轨的重担。 长江上总共...
                            </p>
                            <div class="meta">
                              <a class="nickname" target="_blank" href="/u/b3b2c03354f3">吴晓布</a>
                                <a target="_blank" href="/p/3b4b5ac2ea68#comments">
                                  <i class="iconfont ic-list-comments"></i> 34
                        </a>      <span><i class="iconfont ic-list-like"></i> 37</span>
                                <span><i class="iconfont ic-list-money"></i> 2</span>
                            </div>
                          </div>
                        </li>
                    </ul>
                    <nav aria-label="Page navigation example">
                      <ul class="pagination">
                        <li class="page-item">
                          <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                          </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                          <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                          </a>
                        </li>
                      </ul>
                    </nav>
                </aside>
                <aside class="span4 page-sidebar">
                    <section class="widget">
                        当前搜索：<span id="search">全部</span>&nbsp;&nbsp;<a href="javascript:resetSearch()">重置</a>
                    </section>
                    <section class="widget">
                        <h3 class="title">分类</h3>
                        <div class="tagcloud" id="category-links">
                            <a href="#" class="btn btn-mini">basic</a>
                        </div>
                    </section>
                    <section class="widget">
                        <h3 class="title">Tags</h3>
                        <div class="tagcloud" id="tag-links">
                            <a href="#" class="btn btn-mini">basic</a>
                        </div>
                    </section>
{#                    <section class="widget">#}
{#                        <div class="quick-links-widget">#}
{#                            <h3 class="title">热门文章</h3>#}
{#                            <ul id="menu-quick-links" class="menu clearfix">#}
{#                                <li><a href="index-2.html">Home</a></li>#}
{#                                <li><a href="articles-list.html">Articles List</a></li>#}
{#                                <li><a href="faq.html">FAQs</a></li>#}
{#                                <li><a href="contact.html">Contact</a></li>#}
{#                            </ul>#}
{#                        </div>#}
{#                    </section>#}
{#                    <section class="widget">#}
{#                        <div class="quick-links-widget">#}
{#                            <h3 class="title">最近发布</h3>#}
{#                            <ul id="menu-quick-links" class="menu clearfix">#}
{#                                <li><a href="index-2.html">Home</a></li>#}
{#                                <li><a href="articles-list.html">Articles List</a></li>#}
{#                                <li><a href="faq.html">FAQs</a></li>#}
{#                                <li><a href="contact.html">Contact</a></li>#}
{#                            </ul>#}
{#                        </div>#}
{#                    </section>#}
                </aside>
            </div>
        </div>
    </div>
    <!-- End of Page Container -->

    <script src="{% static 'js/jquery.tmpl.js' %}"></script>
    <script id="blogTmpl" type="text/x-jquery-tmpl">
        <li id="note-28491853" data-note-id="28491853" class="have-img">
{#            <a class="wrap-img" href="/p/3b4b5ac2ea68" target="_blank">#}
{#              <img class="  img-blur-done" src="//upload-images.jianshu.io/upload_images/3343569-4bcf991e16d299a1?imageMogr2/auto-orient/strip|imageView2/1/w/300/h/240" alt="120">#}
{#            </a>#}
          <div class="content">
            <a class="title" href="/${id}">${title}</a>
            <p class="abstract">
              随处可见的长江大桥 全国的城市里，只有重庆的长江大桥最多，建好的有36座。重庆是个两江环绕的山城，桥担负着行车、行人、行轻轨的重担。 长江上总共...
            </p>
            <div class="meta">
              <a class="nickname" target="_blank" href="/u/b3b2c03354f3">吴晓布</a>
                <a target="_blank" href="/p/3b4b5ac2ea68#comments">
                  <i class="iconfont ic-list-comments"></i> 34
                </a>
                <span><i class="iconfont ic-list-like"></i> 37</span>
                <span><i class="iconfont ic-list-money"></i> 2</span>
            </div>
          </div>
        </li>
    </script>
    <script id="categoryTmpl" type="text/x-jquery-tmpl">
        <a href="javascript:selTag(this, '?search=${$data}')" class="btn btn-mini">${$data}</a>
{#        <li><a href="javascript:fetchList('?search=${$data}')">${$data}</a></li>#}
    </script>
    <script id="tagTmpl" type="text/x-jquery-tmpl">
        <a onclick="selTag(this, '?search=${$data}')" class="btn btn-mini">${$data}</a>
{#        <li><a href="javascript:fetchList('?search=${$data}')">${$data}</a></li>#}
    </script>
    <script>
        function renderList(blogs) {
            $("#list_content").empty();
            $("#blogTmpl").tmpl(blogs).appendTo("#list_content");
        }

        function fetchList(queryString) {
            queryString = queryString ? queryString : '';
            if(queryString) {
                $('#search').html(queryString);
            }
            $.ajax({
                url: '/api/articles' + queryString,
                type: 'GET',
                success: function (res) {
                    if (res.code === 0) {
                        renderList(res.data);
                    } else {
                        console.log('获取失败');
                    }
                }
            });
        }

        function selTag(ele, queryString) {
            // 清除其他选中，并设置当前选中
            $('#tag-links>a').removeClass('active');
            if(queryString != $('#search').html()) {
                $(ele).addClass('active');
            } else {
                queryString = '';
                $('#search').html('全部');
            }
            fetchList(queryString)
        }

        function resetSearch() {
            $('#search').html('全部');
            fetchList();
        }

        function renderCategorys() {
            $.ajax({
                url: '/categorys',
                type: 'GET',
                success: function (res) {
                    if (res.code === 0) {
                        $("#category-links").empty();
                        $("#categoryTmpl").tmpl(res.data).appendTo("#category-links");
                    } else {
                        console.log('获取失败');
                    }
                }
            });
        }

        function renderTags() {
            $.ajax({
                url: 'tags',
                type: 'GET',
                success: function (res) {
                    if (res.code === 0) {
                        $("#tag-links").empty();
                        $("#tagTmpl").tmpl(res.data).appendTo("#tag-links");
                    } else {
                        console.log('获取失败');
                    }
                }
            });
        }


        function init() {
            renderCategorys();
            renderTags();
            fetchList();
        }

        init();

    </script>
{% endblock %}